services:
  db_darkaccess:
    image: costaluan/db_darkaccess
    container_name: db_darkaccess
    environment:
      POSTGRES_USER: pinguin
      POSTGRES_PASSWORD: postgress_pinguin_77
      POSTGRES_DB: darkaccess
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - darkaccess-net
    ports:
      - "5432:5432"

  darkaccess-backend:
    build: ./DarkAccess/Back-End
    container_name: darkaccess-backend
    ports:
      - "3001:3001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - ./DarkAccess/Back-End:/app
    environment:
      DB_HOST: db_darkaccess
      DB_USER: pinguin
      DB_PASS: postgress_pinguin_77
      DB_NAME: darkaccess
      DB_PORT: 5432
      API_HOST: 34.132.60.57
      API_PORT: 3001
    depends_on:
      - db_darkaccess
    networks:
      - darkaccess-net
  traefik:
    image: traefik:v3.0
    command:
      - "--providers.docker=true"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml"
      - "./traefik/dynamic.yml:/etc/traefik/dynamic.yml"
      - "./traefik/acme.json:/acme.json"
    networks:
      - darkaccess-net
      - challenge-net

networks:
  darkaccess-net:
    driver: bridge

  challenge-net:
    driver: bridge
    name: challenge-net
    
volumes:
  db_data:
