name: GCP-Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Commit pushed to main branch
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}      
        username: ${{ secrets.USER }}   
        key: ${{ secrets.SSH }} 
        port: 22        
        script: |
          echo "Conectando ao projeto!"
          cd ${{ secrets.project }}
          echo "Realizando o pull das últimas alterações..."
          git pull origin main
          echo "Ultimas alterações aplicadas com sucesso!!!"